services:
  - type: web
    name: majic-breaches-revolt-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: false
